# Generated by Django 4.1.1 on 2022-12-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_of_activities', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (2, 'Archived'), (1, 'Published')], default=0),
        ),
    ]
