# Generated by Django 3.2.4 on 2022-12-30 08:36

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20221230_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
