# Generated by Django 3.2.4 on 2022-12-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_postfilecontent_course_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfilecontent',
            options={},
        ),
    ]
