# Generated by Django 3.2.4 on 2022-12-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_postfilecontent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfilecontent',
            options={'ordering': ['-posted'], 'verbose_name_plural': 'Materials'},
        ),
    ]
