# Generated by Django 3.2.4 on 2022-12-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_auto_20221230_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='user',
        ),
    ]
