# Generated by Django 3.2.4 on 2023-01-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_remove_module_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='hours',
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (2, 'Archived'), (1, 'Published')], default=1),
        ),
    ]
